//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.4.2+d920e93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About</summary>
	[PublishedModel("about")]
	public partial class About : PublishedContentModel, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		public new const string ModelTypeAlias = "about";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<About, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public About(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// AboutBenefitdeDesc1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitdeDesc1")]
		public virtual string AboutBenefitdeDesc1 => this.Value<string>(_publishedValueFallback, "aboutBenefitdeDesc1");

		///<summary>
		/// AboutBenefitdeDesc2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitdeDesc2")]
		public virtual string AboutBenefitdeDesc2 => this.Value<string>(_publishedValueFallback, "aboutBenefitdeDesc2");

		///<summary>
		/// AboutBenefitdeDesc3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitdeDesc3")]
		public virtual string AboutBenefitdeDesc3 => this.Value<string>(_publishedValueFallback, "aboutBenefitdeDesc3");

		///<summary>
		/// AboutBenefitDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitDesc")]
		public virtual string AboutBenefitDesc => this.Value<string>(_publishedValueFallback, "aboutBenefitDesc");

		///<summary>
		/// AboutBenefitIcon1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitIcon1")]
		public virtual string AboutBenefitIcon1 => this.Value<string>(_publishedValueFallback, "aboutBenefitIcon1");

		///<summary>
		/// AboutBenefitIcon2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitIcon2")]
		public virtual string AboutBenefitIcon2 => this.Value<string>(_publishedValueFallback, "aboutBenefitIcon2");

		///<summary>
		/// AboutBenefitIcon3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitIcon3")]
		public virtual string AboutBenefitIcon3 => this.Value<string>(_publishedValueFallback, "aboutBenefitIcon3");

		///<summary>
		/// AboutBenefitImage1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBenefitImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBenefitImage1");

		///<summary>
		/// AboutBenefitImage2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBenefitImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBenefitImage2");

		///<summary>
		/// AboutBenefitImage3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBenefitImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBenefitImage3");

		///<summary>
		/// AboutBenefitName1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitName1")]
		public virtual string AboutBenefitName1 => this.Value<string>(_publishedValueFallback, "aboutBenefitName1");

		///<summary>
		/// AboutBenefitName2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitName2")]
		public virtual string AboutBenefitName2 => this.Value<string>(_publishedValueFallback, "aboutBenefitName2");

		///<summary>
		/// AboutBenefitName3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitName3")]
		public virtual string AboutBenefitName3 => this.Value<string>(_publishedValueFallback, "aboutBenefitName3");

		///<summary>
		/// AboutBenefitTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBenefitTitle")]
		public virtual string AboutBenefitTitle => this.Value<string>(_publishedValueFallback, "aboutBenefitTitle");

		///<summary>
		/// AboutConuterSectionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutConuterSectionTitle")]
		public virtual string AboutConuterSectionTitle => this.Value<string>(_publishedValueFallback, "aboutConuterSectionTitle");

		///<summary>
		/// AboutCounterIcon1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCountericon1")]
		public virtual string AboutCountericon1 => this.Value<string>(_publishedValueFallback, "aboutCountericon1");

		///<summary>
		/// AboutCounterIcon2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCountericon2")]
		public virtual string AboutCountericon2 => this.Value<string>(_publishedValueFallback, "aboutCountericon2");

		///<summary>
		/// AboutCounterIcon3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterIcon3")]
		public virtual string AboutCounterIcon3 => this.Value<string>(_publishedValueFallback, "aboutCounterIcon3");

		///<summary>
		/// AboutCounterIcon4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterIcon4")]
		public virtual string AboutCounterIcon4 => this.Value<string>(_publishedValueFallback, "aboutCounterIcon4");

		///<summary>
		/// AboutCounterNo1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterNo1")]
		public virtual string AboutCounterNo1 => this.Value<string>(_publishedValueFallback, "aboutCounterNo1");

		///<summary>
		/// AboutCounterNo2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterNo2")]
		public virtual string AboutCounterNo2 => this.Value<string>(_publishedValueFallback, "aboutCounterNo2");

		///<summary>
		/// AboutCounterNo3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterNo3")]
		public virtual string AboutCounterNo3 => this.Value<string>(_publishedValueFallback, "aboutCounterNo3");

		///<summary>
		/// AboutCounterNo4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterNo4")]
		public virtual string AboutCounterNo4 => this.Value<string>(_publishedValueFallback, "aboutCounterNo4");

		///<summary>
		/// AboutCounterTitle1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterTitle1")]
		public virtual string AboutCounterTitle1 => this.Value<string>(_publishedValueFallback, "aboutCounterTitle1");

		///<summary>
		/// AboutCounterTitle2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterTitle2")]
		public virtual string AboutCounterTitle2 => this.Value<string>(_publishedValueFallback, "aboutCounterTitle2");

		///<summary>
		/// AboutCounterTitle3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterTitle3")]
		public virtual string AboutCounterTitle3 => this.Value<string>(_publishedValueFallback, "aboutCounterTitle3");

		///<summary>
		/// AboutCounterTitle4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCounterTitle4")]
		public virtual string AboutCounterTitle4 => this.Value<string>(_publishedValueFallback, "aboutCounterTitle4");

		///<summary>
		/// AboutDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutDesc")]
		public virtual string AboutDesc => this.Value<string>(_publishedValueFallback, "aboutDesc");

		///<summary>
		/// AboutHeaderImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutHeaderImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutHeaderImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutHeaderImage");

		///<summary>
		/// AboutHeaderTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutHeaderTitle")]
		public virtual string AboutHeaderTitle => this.Value<string>(_publishedValueFallback, "aboutHeaderTitle");

		///<summary>
		/// AboutMissionDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutMissionDesc")]
		public virtual string AboutMissionDesc => this.Value<string>(_publishedValueFallback, "aboutMissionDesc");

		///<summary>
		/// AboutMissionImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutMissionImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutMissionImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutMissionImage");

		///<summary>
		/// AboutMissionSectionDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutMissionSectionDesc")]
		public virtual string AboutMissionSectionDesc => this.Value<string>(_publishedValueFallback, "aboutMissionSectionDesc");

		///<summary>
		/// AboutMissionSectionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutMissionSectionTitle")]
		public virtual string AboutMissionSectionTitle => this.Value<string>(_publishedValueFallback, "aboutMissionSectionTitle");

		///<summary>
		/// AboutMissionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutMissionTitle")]
		public virtual string AboutMissionTitle => this.Value<string>(_publishedValueFallback, "aboutMissionTitle");

		///<summary>
		/// AboutOurTeams
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutOurTeams")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel AboutOurTeams => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "aboutOurTeams");

		///<summary>
		/// AboutOurTeamsDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutOurTeamsDesc")]
		public virtual string AboutOurTeamsDesc => this.Value<string>(_publishedValueFallback, "aboutOurTeamsDesc");

		///<summary>
		/// AboutOurTeamsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutOurTeamsTitle")]
		public virtual string AboutOurTeamsTitle => this.Value<string>(_publishedValueFallback, "aboutOurTeamsTitle");

		///<summary>
		/// AboutPartnerDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutPartnerDesc")]
		public virtual string AboutPartnerDesc => this.Value<string>(_publishedValueFallback, "aboutPartnerDesc");

		///<summary>
		/// AboutPartnerImages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutPartnerImages")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops> AboutPartnerImages => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops>>(_publishedValueFallback, "aboutPartnerImages");

		///<summary>
		/// AboutPartnerTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutPartnerTitle")]
		public virtual string AboutPartnerTitle => this.Value<string>(_publishedValueFallback, "aboutPartnerTitle");

		///<summary>
		/// AboutSectionDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionDesc")]
		public virtual string AboutSectionDesc => this.Value<string>(_publishedValueFallback, "aboutSectionDesc");

		///<summary>
		/// AboutSectionImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutSectionImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutSectionImage");

		///<summary>
		/// AboutSectionSubTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionSubTitle")]
		public virtual string AboutSectionSubTitle => this.Value<string>(_publishedValueFallback, "aboutSectionSubTitle");

		///<summary>
		/// AboutSectionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionTitle")]
		public virtual string AboutSectionTitle => this.Value<string>(_publishedValueFallback, "aboutSectionTitle");

		///<summary>
		/// AboutSubTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSubTitle")]
		public virtual string AboutSubTitle => this.Value<string>(_publishedValueFallback, "aboutSubTitle");

		///<summary>
		/// AboutTestimonialDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTestimonialDesc")]
		public virtual string AboutTestimonialDesc => this.Value<string>(_publishedValueFallback, "aboutTestimonialDesc");

		///<summary>
		/// AboutTestimonials
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTestimonials")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel AboutTestimonials => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "aboutTestimonials");

		///<summary>
		/// AboutTestimonialTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTestimonialTitle")]
		public virtual string AboutTestimonialTitle => this.Value<string>(_publishedValueFallback, "aboutTestimonialTitle");

		///<summary>
		/// AboutTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTitle")]
		public virtual string AboutTitle => this.Value<string>(_publishedValueFallback, "aboutTitle");

		///<summary>
		/// AboutVisionDesc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutVisionDesc")]
		public virtual string AboutVisionDesc => this.Value<string>(_publishedValueFallback, "aboutVisionDesc");

		///<summary>
		/// AboutVisionImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutVisionImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutVisionImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutVisionImage");

		///<summary>
		/// AboutVisionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutVisionTitle")]
		public virtual string AboutVisionTitle => this.Value<string>(_publishedValueFallback, "aboutVisionTitle");

		///<summary>
		/// Canonical: Used in SEO, see: http://googlewebmastercentral.blogspot.com/2009/02/specify-your-canonical.html
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("Canonical")]
		public virtual string Canonical => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetCanonical(this, _publishedValueFallback);

		///<summary>
		/// Facebook App ID: In order to use Facebook Insights you must add the app ID to your page. Insights lets you view analytics for traffic to your site from Facebook. Find the app ID in your App Dashboard.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("FBAppID")]
		public virtual string FbappID => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetFbappID(this, _publishedValueFallback);

		///<summary>
		/// Hide From Xml Sitemap: whether to show this page on the XML sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[ImplementPropertyType("hideFromXmlSitemap")]
		public virtual bool HideFromXmlSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetHideFromXmlSitemap(this, _publishedValueFallback);

		///<summary>
		/// Menu Display Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuDisplayImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MenuDisplayImage => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMenuDisplayImage(this, _publishedValueFallback);

		///<summary>
		/// Menu Display Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuDisplayName")]
		public virtual string MenuDisplayName => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMenuDisplayName(this, _publishedValueFallback);

		///<summary>
		/// Author: The name of the page’s author.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaAuthor")]
		public virtual string MetaAuthor => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMetaAuthor(this, _publishedValueFallback);

		///<summary>
		/// Meta Description: A brief description of the content on your page. This text is shown below the title in a google search result The ideal length is between 130 and 155 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Meta keywords: Keywords that describe the content of the page. This is considered optional since most modern search engines don't use this anymore.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaKeywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MetaKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMetaKeywords(this, _publishedValueFallback);

		///<summary>
		/// Meta Tag Block: Can input any text what you want to render in the HTML HEAD. For example:  {meta name="keywords" content="{Title}"}{meta http-equiv="charset" content="{Charset}"}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTagBlock")]
		public virtual string MetaTagBlock => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetMetaTagBlock(this, _publishedValueFallback);

		///<summary>
		/// Description: A brief description of the content, usually between 2 and 4 sentences. This will displayed below the title of the post on Facebook.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGDescription")]
		public virtual string Ogdescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOgdescription(this, _publishedValueFallback);

		///<summary>
		/// Image: The URL of the image that appears when someone shares the content to Facebook.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Ogimage => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOgimage(this, _publishedValueFallback);

		///<summary>
		/// Locale: The locale of the resource. Defaults to en_US.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGLocale")]
		public virtual string Oglocale => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOglocale(this, _publishedValueFallback);

		///<summary>
		/// Title: The title of your article without any branding such as your site name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGTitle")]
		public virtual string Ogtitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOgtitle(this, _publishedValueFallback);

		///<summary>
		/// Type: The type of media of your content. This tag impacts how your content shows up in News Feed. If you don't specify a type,the default is website. Each URL should be a single object, so multiple og:type values are not possible.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGType")]
		public virtual string Ogtype => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOgtype(this, _publishedValueFallback);

		///<summary>
		/// URL: The canonical URL for your page. This should be the undecorated URL, without session variables, user identifying parameters, or counters. Likes and Shares for this URL will aggregate at this URL. For example, mobile domain URLs should point to the desktop version of the URL as the canonical URL to aggregate Likes and Shares across different versions of the page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OGURL")]
		public virtual string Ogurl => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOgurl(this, _publishedValueFallback);

		///<summary>
		/// Page Title: The title of the page, this is also the first text in a google search result.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetPageTitle(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Change Frequency: How often will the content of this page change?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public virtual string SearchEngineChangeFrequency => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Relative Priority: Indicate the relative priority of this page compared to the rest of the site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public virtual decimal SearchEngineRelativePriority => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineRelativePriority(this, _publishedValueFallback);

		///<summary>
		/// Card Type: Select the twitter card type you need to use.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterCardType")]
		public virtual string TwitterCardType => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterCardType(this, _publishedValueFallback);

		///<summary>
		/// Description: A description that concisely summarizes the content as appropriate for presentation within a Tweet. You should not re-use the title as the description or use this field to describe the general services provided by the website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterDescription")]
		public virtual string TwitterDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterDescription(this, _publishedValueFallback);

		///<summary>
		/// Image: A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TwitterImage => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterImage(this, _publishedValueFallback);

		///<summary>
		/// Image Alt: A text description of the image conveying the essential nature of an image to users who are visually impaired. Maximum 420 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterImageAlt")]
		public virtual string TwitterImageAlt => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterImageAlt(this, _publishedValueFallback);

		///<summary>
		/// Site: The Twitter @username the card should be attributed to.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterSite")]
		public virtual string TwitterSite => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterSite(this, _publishedValueFallback);

		///<summary>
		/// Title: A concise title for the related content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("TwitterTitle")]
		public virtual string TwitterTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTwitterTitle(this, _publishedValueFallback);

		///<summary>
		/// Hide From Navigation: Hide From Navigation Main Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.4.2+d920e93")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetUmbracoNaviHide(this, _publishedValueFallback);
	}
}
